spring:
  application:
    name: zuul-server
server:
  port: 5555
  servlet:
    context-path: /cloud
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

# http"//localhost:5555/cloud[/endpoint/]
zuul:
  routes:
    order-ms:
      path: orders/**
      serviceId: order-ms

    product-ms:
      path: product/**
      serviceId: product-ms

    customer-ms:
      path: customer/**
      serviceId: customer-ms

    feign-ms:
     path: feign/**
     serviseId: feign-ms

  sensitiveHeaders: Cookie, Set-Cookie
