server:
  port: 0
  servlet:
    context-path: /orders

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Order_ms?currentSchema=order_schema_ms
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  application:
    name: order-ms
  jpa:
    show-sql: true
  cloud:
    discovery:
      enabled: true
eureka:
  client:
    fetch-registry: true
    service-url.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true