server:
  port: 0
  servlet:
    context-path: /feign
spring:
  application:
    name: feign-ms
eureka:
  client:
    fetch-registry: true
    service-url.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}