server:
  port: 0
  servlet:
    context-path: /customer


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Customer_ms?currentSchema=customer_schema_ms
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
  application:
    name: customer-ms
jwt:
  secret: lsjdlfjlsjdfljsdllkfmlksdfojspodjf

eureka:
  client:
    fetch-registry: true
    service-url.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}